esphome:
  name: dual_relay_module
  platform: ESP8266
  board: nodemcuv2  # Adjust the board type based on your ESP8266 variant

wifi:
  ssid: "YOUR_WIFI_SSID"
  password: "YOUR_WIFI_PASSWORD"

api:

ota:

binary_sensor:
  - platform: status
    name: "Dual Relay Module Status"

output:
  - platform: gpio
    pin: D0
    id: relay_1
    inverted: true
  - platform: gpio
    pin: D1
    id: relay_2
    inverted: true

switch:
  - platform: template
    name: "Relay 1"
    id: relay1_output
    turn_on_action:
      - output.turn_on: relay_1
    turn_off_action:
      - output.turn_off: relay_1
  - platform: template
    name: "Relay 2"
    id: relay2_output
    turn_on_action:
      - output.turn_on: relay_2
    turn_off_action:
      - output.turn_off: relay_2
#Hardware Connection 
#3V - VCC
#GND - GND
#D0 - IN1
#D1 - IN2